repository:
  path: github.com/tellytv/telly
build:
  flags: -a -tags netgo
  ldflags: |
    -X github.com/prometheus/common/version.Version={{.Version}}
    -X github.com/prometheus/common/version.Revision={{.Revision}}
    -X github.com/prometheus/common/version.Branch={{.Branch}}
    -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
    -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
  files:
    - LICENSE
    - NOTICE
crossbuild:
  platforms:
    - linux/amd64
    - linux/386
    - darwin/amd64
    - darwin/386
    - windows/amd64
    - windows/386
    - freebsd/amd64
    - freebsd/386
    - linux/arm
    - linux/arm64
